#define CMD_ID_LOGIN_GET_REQ        1000
#define CMD_ID_LOGIN_GET_RES        1001
#define CMD_ID_LOGIN_SET_REQ        1002
#define CMD_ID_LOGIN_SET_RES        1003
#define CMD_ID_USER_GET_REQ        1004
#define CMD_ID_USER_GET_RES        1005
#define CMD_ID_USER_SET_REQ        1006
#define CMD_ID_USER_SET_RES        1007
#define CMD_ID_VIDEO_GET_REQ        1008
#define CMD_ID_VIDEO_GET_RES        1009
#define CMD_ID_VIDEO_SET_REQ        1010
#define CMD_ID_VIDEO_SET_RES        1011
#define CMD_ID_NETWORK_GET_REQ        1012
#define CMD_ID_NETWORK_GET_RES        1013
#define CMD_ID_NETWORK_SET_REQ        1014
#define CMD_ID_NETWORK_SET_RES        1015
#define CMD_ID_ALERT_GET_REQ        1016
#define CMD_ID_ALERT_GET_RES        1017
#define CMD_ID_ALERT_SET_REQ        1018
#define CMD_ID_ALERT_SET_RES        1019
#define CMD_ID_STORE_GET_REQ        1020
#define CMD_ID_STORE_GET_RES        1021
#define CMD_ID_STORE_SET_REQ        1022
#define CMD_ID_STORE_SET_RES        1023
#define CMD_ID_SYS_GET_REQ        1024
#define CMD_ID_SYS_GET_RES        1025
#define CMD_ID_SYS_SET_REQ        1026
#define CMD_ID_SYS_SET_RES        1027
#define CMD_ID_RTV_START_GET_REQ        1028
#define CMD_ID_RTV_START_GET_RES        1029
#define CMD_ID_RTV_START_SET_REQ        1030
#define CMD_ID_RTV_START_SET_RES        1031
#define CMD_ID_HTV_START_GET_REQ        1032
#define CMD_ID_HTV_START_GET_RES        1033
#define CMD_ID_HTV_START_SET_REQ        1034
#define CMD_ID_HTV_START_SET_RES        1035
#define CMD_ID_HTV_END_GET_REQ        1036
#define CMD_ID_HTV_END_GET_RES        1037
#define CMD_ID_HTV_END_SET_REQ        1038
#define CMD_ID_HTV_END_SET_RES        1039
#define CMD_ID_PIC_START_GET_REQ        1040
#define CMD_ID_PIC_START_GET_RES        1041
#define CMD_ID_PIC_START_SET_REQ        1042
#define CMD_ID_PIC_START_SET_RES        1043
#define CMD_ID_PTZ_CONTROL_GET_REQ        1044
#define CMD_ID_PTZ_CONTROL_GET_RES        1045
#define CMD_ID_PTZ_CONTROL_SET_REQ        1046
#define CMD_ID_PTZ_CONTROL_SET_RES        1047
#define CMD_ID_SYS_QUIT_GET_REQ        1048
#define CMD_ID_SYS_QUIT_GET_RES        1049
#define CMD_ID_SYS_QUIT_SET_REQ        1050
#define CMD_ID_SYS_QUIT_SET_RES        1051
#define CMD_ID_LOG_GET_REQ        1052
#define CMD_ID_LOG_GET_RES        1053
#define CMD_ID_LOG_SET_REQ        1054
#define CMD_ID_LOG_SET_RES        1055
#define CMD_ID_USB_REMOVE_GET_REQ        1056
#define CMD_ID_USB_REMOVE_GET_RES        1057
#define CMD_ID_USB_REMOVE_SET_REQ        1058
#define CMD_ID_USB_REMOVE_SET_RES        1059
#define CMD_ID_HB_GET_REQ        1060
#define CMD_ID_HB_GET_RES        1061
#define CMD_ID_HB_SET_REQ        1062
#define CMD_ID_HB_SET_RES        1063
#define CMD_ID_DEF_CONFIG_GET_REQ        1064
#define CMD_ID_DEF_CONFIG_GET_RES        1065
#define CMD_ID_DEF_CONFIG_SET_REQ        1066
#define CMD_ID_DEF_CONFIG_SET_RES        1067
#define CMD_ID_MD_REPORT_GET_REQ        1068
#define CMD_ID_MD_REPORT_GET_RES        1069
#define CMD_ID_MD_REPORT_SET_REQ        1070
#define CMD_ID_MD_REPORT_SET_RES        1071
#define CMD_ID_ALARM_DISK_GET_REQ        1072
#define CMD_ID_ALARM_DISK_GET_RES        1073
#define CMD_ID_ALARM_DISK_SET_REQ        1074
#define CMD_ID_ALARM_DISK_SET_RES        1075
#define CMD_ID_TIME_SYN_GET_REQ        1076
#define CMD_ID_TIME_SYN_GET_RES        1077
#define CMD_ID_TIME_SYN_SET_REQ        1078
#define CMD_ID_TIME_SYN_SET_RES        1079
#define CMD_ID_ALARM_ERROR_GET_REQ        1080
#define CMD_ID_ALARM_ERROR_GET_RES        1081
#define CMD_ID_ALARM_ERROR_SET_REQ        1082
#define CMD_ID_ALARM_ERROR_SET_RES        1083
#define CMD_ID_PROCESS_INFO_GET_REQ        1084
#define CMD_ID_PROCESS_INFO_GET_RES        1085
#define CMD_ID_PROCESS_INFO_SET_REQ        1086
#define CMD_ID_PROCESS_INFO_SET_RES        1087

